### ISSUE TITLE
WSPR 20m qrg correct?

### ISSUE THREAD

**Issue by dl9sau** [lightaprs/LightAPRS-W-1.0#3]
Question / I'm unsure. The definition
#define WSPR_DEFAULT_FREQ       14097200UL //20m band
seems 100 Hz too high. My lightaprs-w was (with his freq offset and the offset of my receiver) about 70 Hz out of receiption-band in WSJT-X.

#define WSPR_DEFAULT_FREQ       14097100UL //20m band
seems correct.
With this, it has the normal 1,5 KHz offset to the dial frequency we also find at all other WSPR_DEFAULT_FREQ examples for the other bands.

**Comment by lightaprs** [comment]
Thanks for the fix :)
