### ISSUE TITLE
Issue power

### ISSUE THREAD

**Issue by neffen37** [lightaprs/LightAPRS-W-1.0#9]
hello I have a problem with a Light APRS (+WSPR) tracker 1.0 I followed the procedure to the letter I connected the two antennas with sma sockets I compiled and modified the settings that I needed I have upload the code I then connected a battery but I have nothing on the serial port no info, I checked on the card I have 3.3v there is no LED on the card?
waiting for an answer.
![2024-05-13 20_05_21-LightAPRS-W-pico-balloon _ Arduino IDE 2 2 1](https://github.com/lightaprs/LightAPRS-W-1.0/assets/29715586/559a675a-9fb1-417e-9caa-09c0d02c120d)
![20240513_200439](https://github.com/lightaprs/LightAPRS-W-1.0/assets/29715586/5c79ff1b-2458-4d03-b9ac-c0ac9f216483)

cordialy

**Comment by lightaprs** [comment]
Hi,

* There is no LED on board for power saving (important for solar based pico
balloon flights)
* To keep board lightweight, on-board GPS antenna is passive, therefore for
a GPS fix, you should test it outdoors, not indoorS. For a location beacon,
GPS fix is needed.
* Check Arduino Serial Console for logs, for detailed logs enable DEVMODE
* After a GPS fix, if there is a iGate or Digipeater in your neighborhood,
you should see your beacon on aprs.fi

TA2MUN
